# Data wrangling with Pandas exercise
* For this exercise we will be using the `listings.csv` data file.

In [52]:
import pandas as pd
import numpy as np

# Load in the data file using `pd.read_csv()`

In [1]:
# Load data here
import pandas as pd
import numpy as np
df = pd.read_csv('data/listings.csv', sep=',')

## Exercise 2 - Filtering

Return the following subsets of the dataframe.

1. How many listings are there with a price less than 100? 


2. Find how many listings there are in just Brooklyn.


3. Find how many listings there are in Brooklyn with a price less than 100.


4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.
    * Count the amout of names each time appears.


5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  The prices for all other listings should be the same as the were before. 


6. What % of the rooms are private, and what % of the rooms are shared.  
    * Hint, use `.value_counts()`


Challenge:
* Listings with the word brownstone in the name (hint to come, might move this one later if needed)
    * hint... build a function to check for 'brownstone' and apply that function OR  `df.name.str.????`

In [4]:
# 1. How many listings are there with a price less than 100? 
select_condition = df['price'] < 100
print("Listings less than 100: "+ str(len(df[select_condition])))

Listings less than 100: 22778

In [5]:
# 2. Make a new DataFrame of listings in Brooklyn named `df_bk` 
# and find how many listings in just Brooklyn of less than $100.
select_condition2 = df['neighbourhood_group'] == "Brooklyn"

df_bk = df[select_condition2]
print("Listings in Brooklyn: "+ str(len(df[select_condition2])))

Listings in Brooklyn: 18632

In [8]:
# 3. Find how many listings there are in Brooklyn with a price less than 100.

print("Listings in Brooklyn & less than 100: "+ str(len(df[select_condition & select_condition2])))
df[select_condition & select_condition2]

Listings in Brooklyn & less than 100: 10473

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,29,50,2019-12-02,0.37,1,365
8,5803,"Lovely Room 1, Garden, Best Area, Legal rental",9744,Laurie,Brooklyn,South Slope,40.66829,-73.98779,Private room,88,4,180,2020-03-18,1.31,3,344
21,10452,Large B&B Style rooms,35935,Angela,Brooklyn,Bedford-Stuyvesant,40.68310,-73.95473,Private room,70,3,75,2019-10-12,0.60,2,365
22,10962,"Lovely Room 2; Garden; Best area, Legal",9744,Laurie,Brooklyn,South Slope,40.66869,-73.98780,Private room,88,4,180,2020-08-03,1.36,3,365
27,12627,Entire apartment in central Brooklyn neighborh...,49670,Rana,Brooklyn,Prospect-Lefferts Gardens,40.65944,-73.96238,Entire home/apt,95,30,13,2019-12-05,0.36,1,156
32,13394,Fort Greene brownstone,52335,Alexander,Brooklyn,Fort Greene,40.69142,-73.97376,Private room,70,1,143,2020-03-19,1.11,1,170
34,13808,Blue Room for 2 in Brownstone for $1350 monthly,54275,JT And Tiziana,Brooklyn,Bedford-Stuyvesant,40.68064,-73.94039,Private room,81,2,141,2020-07-12,1.14,3,339
42,15385,"Very, very cozy place",60252,Cristina,Brooklyn,Williamsburg,40.71185,-73.96204,Private room,80,7,49,2020-02-07,0.39,1,229
48,16338,Double Room w Private Deck Clinton Hill Best Area,63613,Patricia,Brooklyn,Clinton Hill,40.69000,-73.96788,Private room,55,7,28,2020-04-01,0.22,2,264
58,17747,BLUE TRIM GUEST HOUSE,68599,George,Brooklyn,Clinton Hill,40.68346,-73.96374,Private room,75,2,128,2020-03-08,1.01,1,364
69,20611,Cozy Bedroom in Williamsburg 3 BR,72014,Yvelisa,Brooklyn,Williamsburg,40.71156,-73.96218,Private room,85,3,193,2019-12-18,1.52,2,365
70,20717,Room in Brownstone B/Q feet away,78353,Guillaume,Brooklyn,Prospect Heights,40.67832,-73.97243,Private room,85,1,43,2020-03-17,0.52,3,312
71,20724,Sunny room+Pvte office in huge loft,961342,Augustin,Brooklyn,Bushwick,40.70032,-73.93830,Private room,45,5,30,2019-11-10,0.30,1,345
72,20755,"Large Parlor Room, Landmark Home 1 block to PRATT",51038,Erica,Brooklyn,Clinton Hill,40.68634,-73.96600,Private room,98,7,19,2020-04-25,0.20,5,349
73,20913,Charming 1 bed GR8 WBurg LOCATION!,79402,Christiana,Brooklyn,Williamsburg,40.70984,-73.95775,Entire home/apt,80,5,168,2018-07-22,1.40,1,0
83,25406,"Modern Brooklyn Apt., August sublet",105538,Erik,Brooklyn,Williamsburg,40.71459,-73.94844,Entire home/apt,83,30,29,2018-05-26,0.34,1,0
88,26520,"Cozy Room #3, Landmark Home 1 Block to PRATT",51038,Erica,Brooklyn,Clinton Hill,40.68698,-73.96572,Private room,98,2,29,2020-01-02,0.26,5,270
90,26785,Park Slope Green Guest House,42273,Dani,Brooklyn,South Slope,40.66853,-73.98912,Entire home/apt,90,30,470,2020-05-01,3.79,2,212
98,29013,B & B Room 1,35935,Angela,Brooklyn,Bedford-Stuyvesant,40.68332,-73.95470,Private room,70,3,64,2020-01-30,0.52,2,365
100,29628,Sunny Room in New Condo,127608,Chris,Brooklyn,Clinton Hill,40.68414,-73.96351,Private room,89,3,281,2020-02-17,2.26,1,364
102,30031,NYC artists’ loft with roof deck,129352,Sol,Brooklyn,Greenpoint,40.73494,-73.95030,Private room,49,3,196,2020-02-12,1.67,1,0
105,31902,Sanctuary in East Flatbush,137292,Sunder,Brooklyn,Flatlands,40.63188,-73.93248,Private room,80,2,4,2019-10-14,0.03,1,178
106,31994,Room with En Suite Bathroom & Deck,137814,Waldemar,Brooklyn,Clinton Hill,40.68818,-73.96383,Private room,80,2,460,2020-08-02,3.74,2,351
127,39282,“Work-from-home” from OUR home.,168525,Gus,Brooklyn,Williamsburg,40.71088,-73.95055,Private room,50,4,219,2020-07-16,1.79,1,60
145,45556,"Fort Greene, Brooklyn: Center Bedroom",67778,Doug,Brooklyn,Fort Greene,40.68834,-73.97578,Private room,65,2,251,2020-06-26,2.08,2,175
159,53196,Big Room/Washer-Dryer/Wifi/AC/JMZ,247432,Charlotte,Brooklyn,Bedford-Stuyvesant,40.69546,-73.93503,Private room,80,2,11,2017-11-13,0.30,1,0
166,54508,Sml Rm Brst PSl great for longer stays Med/Stu,210746,Kathleen R.,Brooklyn,Prospect Heights,40.67870,-73.97262,Private room,50,2,100,2020-08-15,12.82,3,0
171,55498,Modern comfort in art infused landmark Brownstone,262138,Tami,Brooklyn,Bedford-Stuyvesant,40.68290,-73.93549,Private room,79,14,42,2020-03-15,0.36,1,108
173,55982,Cozy 2 br in sunny Fort Greene apt,264928,Sally,Brooklyn,Fort Greene,40.68656,-73.97525,Private room,85,3,37,2018-12-31,0.31,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46388,44658334,MG-B • Cool room in Brooklyn close to Manhattan,346457583,Alliny,Brooklyn,Bedford-Stuyvesant,40.69317,-73.93883,Private room,41,1,0,NaN,NaN,9,200
46389,44658442,MG-C • Awsome Brklyn room close to Manhattan,346457583,Alliny,Brooklyn,Bedford-Stuyvesant,40.69292,-73.94057,Private room,41,1,0,NaN,NaN,9,210
46390,44658559,Clean Room w/ Outdoor Deck in Brooklyn Brownstone,4393745,Nelson,Brooklyn,Bedford-Stuyvesant,40.68289,-73.95348,Private room,40,4,0,NaN,NaN,1,74
46391,44658641,MG-D • Best Big Romm in Broklyn close to Manha...,346457583,Alliny,Brooklyn,Bedford-Stuyvesant,40.69144,-73.93888,Private room,41,1,0,NaN,NaN,9,209
46392,44658754,MG-E • Best private in Brooklyn close to Subways,346457583,Alliny,Brooklyn,Bedford-Stuyvesant,40.69256,-73.94080,Private room,41,1,0,NaN,NaN,9,203
46394,44659585,"Sunny, Spacious, Safe & Quiet 3-bedroom apt",185022050,Chi,Brooklyn,Bensonhurst,40.61448,-73.98687,Entire home/apt,85,30,0,NaN,NaN,2,365
46398,44661639,"S-2 Small and Comfy Romm, 3 min to the station.",361188882,Pedro,Brooklyn,Brownsville,40.66212,-73.91594,Private room,40,1,0,NaN,NaN,6,364
46399,44661848,2Bed - Home Away from Home in Brooklyn + Wifi,274782993,Imani,Brooklyn,Crown Heights,40.67410,-73.91964,Entire home/apt,90,2,0,NaN,NaN,1,76
46400,44661849,"S4- Cute and Cozy Romm, 3 min to the station",361188882,Pedro,Brooklyn,Brownsville,40.66316,-73.91551,Private room,45,1,0,NaN,NaN,6,349
46404,44662274,S5 - Amazing room close to subway to Manhattan,361188882,Pedro,Brooklyn,Brownsville,40.66212,-73.91527,Private room,45,1,0,NaN,NaN,6,361
46406,44662469,"S1- Great and Spacious Room, 3 minutesto station",361188882,Pedro,Brooklyn,Brownsville,40.66324,-73.91424,Private room,49,1,0,NaN,NaN,6,365
46407,44662666,Unique & beautiful design! Skylights-Washer/dryer,143513836,Elisabeth,Brooklyn,Crown Heights,40.67331,-73.91700,Private room,61,30,0,NaN,NaN,5,240
46408,44662758,"S3- Amazing and Big Room, 3 minutes to the sta...",361188882,Pedro,Brooklyn,Brownsville,40.66222,-73.91561,Private room,45,1,0,NaN,NaN,6,350
46410,44663595,Beautiful and cozy basement in Brooklyn.,361188882,Pedro,Brooklyn,Brownsville,40.66373,-73.91456,Entire home/apt,93,2,0,NaN,NaN,6,363
46427,44678790,Brooklyn Room with a View,198666639,Bernard,Brooklyn,Bedford-Stuyvesant,40.68366,-73.93764,Private room,47,1,0,NaN,NaN,10,178
46428,44679230,Cozy Room next to the subway,198666639,Bernard,Brooklyn,Bedford-Stuyvesant,40.68505,-73.93703,Private room,46,1,0,NaN,NaN,10,151
46429,44679312,Great Room in Brooklyn,198666639,Bernard,Brooklyn,Bedford-Stuyvesant,40.68373,-73.93882,Private room,46,1,0,NaN,NaN,10,173
46437,44683296,"Modern, stunning room; amenities galore;",50831372,Ezra,Brooklyn,Greenpoint,40.73285,-73.95677,Private room,70,180,0,NaN,NaN,1,362
46442,44684912,SUNNY CORNER BEDROOM in Spacious Apartment,32589568,Lauren,Brooklyn,Bay Ridge,40.63819,-74.03190,Entire home/apt,55,30,0,NaN,NaN,2,70
46445,44685535,Spacious private room close to Pratt,358356356,Alex And Vlada,Brooklyn,Bedford-Stuyvesant,40.68864,-73.95172,Private room,36,30,0,NaN,NaN,10,365
46446,44685540,Stylish private room with en-suite close to G ...,358356356,Alex And Vlada,Brooklyn,Bedford-Stuyvesant,40.68963,-73.95180,Private room,45,30,0,NaN,NaN,10,365
46448,44686187,Dream place in East Williamsburg,257056107,Karl,Brooklyn,Williamsburg,40.70100,-73.94234,Entire home/apt,80,60,0,NaN,NaN,1,276
46460,44699634,Cute Clean Brooklyn/Queens Private Space Near ...,349059281,Dino,Brooklyn,Bushwick,40.69751,-73.91131,Private room,41,1,0,NaN,NaN,3,80
46488,44748933,Private bedroom In an apartment with a backyard,358919154,Afradh,Brooklyn,Gowanus,40.66730,-73.99445,Private room,39,1,0,NaN,NaN,2,360
46505,44791984,very convenient area right next to JMZ train,86766592,Gabby,Brooklyn,Bushwick,40.69874,-73.93696,Private room,96,1,0,NaN,NaN,1,174
46510,44798876,Unique & beautiful design! Skylights-Washer/dryer,143513836,Elisabeth,Brooklyn,Crown Heights,40.67156,-73.91651,Private room,61,30,0,NaN,NaN,5,329
46517,44802032,A very large room in Williamsburg,213793805,Omer,Brooklyn,Williamsburg,40.71970,-73.95632,Private room,55,14,0,NaN,NaN,1,45
46518,44802224,Unique & beautiful design! Skylights-Washer/dryer,143513836,Elisabeth,Brooklyn,Crown Heights,40.67302,-73.91695,Private room,61,30,0,NaN,NaN,5,363
46524,44811717,Comfortable safe environment 24hr security camera,362453686,Nicole,Brooklyn,East Flatbush,40.65399,-73.93287,Private room,59,3,0,NaN,NaN,1,90
46526,44818009,"5MIN D/N trains, NEAR THE BEACH, 50’ TO MANHATTAN",48098268,Marina,Brooklyn,Gravesend,40.59945,-73.98209,Private room,66,1,0,NaN,NaN,1,38

In [57]:
# 4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.
list_hosts = ["Michael", "David", "John", "Daniel"]

condition = df.host_name.isin(list_hosts)
df["host_name"][condition].value_counts()

Michael    387
David      348
John       270
Daniel     253
Name: host_name, dtype: int64

In [12]:
# 5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  
# The prices for all other listings should be the same as the were before.
select_condition = df["neighbourhood"] == "Williamsburg"
df["adjusted_price"] = np.where(select_condition, df["price"]+100 , df["price"])

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,adjusted_price
2903,2110145,UWS 1BR w/backyard + block from CP,2151325,Jay And Liz,Manhattan,Upper West Side,40.77782,-73.97848,Entire home/apt,6000,14,17,2015-02-17,0.22,1,359,6000
3062,2243699,"SuperBowl Penthouse Loft 3,000 sqft",1483320,Omri,Manhattan,Little Italy,40.71895,-73.99793,Entire home/apt,5250,1,0,NaN,NaN,1,0,5250
3109,2271504,SUPER BOWL Brooklyn Duplex Apt!!,11598359,Jonathan,Brooklyn,Clinton Hill,40.68766,-73.96439,Entire home/apt,6500,1,0,NaN,NaN,1,0,6500
3635,2953058,Film Location,1177497,Jesse,Brooklyn,Clinton Hill,40.69137,-73.96723,Entire home/apt,8000,1,1,2016-09-15,0.02,10,362,8000
4896,4308991,Sunny Room with Private Bathroom in Great Loca...,6195809,Dean,Manhattan,East Village,40.72607,-73.98867,Private room,9990,4,9,2020-01-03,0.15,1,0,9990
5431,4737930,Spanish Harlem Apt,1235070,Olson,Manhattan,East Harlem,40.79264,-73.93898,Entire home/apt,9999,5,1,2015-01-02,0.01,1,0,9999
10274,9528920,"Quiet, Clean, Lit @ LES & Chinatown",3906464,Amy,Manhattan,Lower East Side,40.71355,-73.98507,Private room,7314,99,6,2016-01-01,0.10,1,83,7314
12954,12520066,Luxury townhouse Greenwich Village,66240032,Linda,Manhattan,Greenwich Village,40.73046,-73.99562,Entire home/apt,6000,1,0,NaN,NaN,1,0,6000
14718,13894339,Luxury 1 bedroom apt. -stunning Manhattan views,5143901,Erin,Brooklyn,Greenpoint,40.73260,-73.95739,Entire home/apt,10000,5,5,2017-07-27,0.11,1,0,10000
14763,13925864,Puerto Plata,58480311,Raquel-Ast,Queens,Long Island City,40.76168,-73.92986,Entire home/apt,10000,2,28,2018-01-03,0.57,1,0,10000
20862,20464496,LaRoom,49519069,Kosta,Queens,Briarwood,40.71050,-73.81589,Private room,9000,5,0,NaN,NaN,1,177,9000
21059,20654227,Fulton 2,100069033,Sarah-2,Brooklyn,Cypress Hills,40.68185,-73.88128,Entire home/apt,6429,2,4,2018-01-03,0.11,1,0,6429
21728,21238053,Broadway 1,153497815,Sarah-B,Brooklyn,Bedford-Stuyvesant,40.68742,-73.91957,Entire home/apt,6143,2,8,2017-12-09,0.23,1,0,6143
23652,22436899,1-BR Lincoln Center,72390391,Jelena,Manhattan,Upper West Side,40.77213,-73.98665,Entire home/apt,10000,30,0,NaN,NaN,1,83,10000
27085,26984880,One Bedroom Penthouse,176952168,Aka,Manhattan,Financial District,40.70729,-74.00728,Entire home/apt,9999,1,0,NaN,NaN,8,0,9999
27087,26985356,One Bedroom Premium Suite,176952168,Aka,Manhattan,Financial District,40.70779,-74.00817,Entire home/apt,9999,1,0,NaN,NaN,8,0,9999
27088,26985402,One Bedroom Suite,176952168,Aka,Manhattan,Financial District,40.70756,-74.00750,Entire home/apt,9999,1,0,NaN,NaN,8,0,9999
27089,26985775,One Bedroom Terrace Penthouse,176952168,Aka,Manhattan,Financial District,40.70720,-74.00699,Entire home/apt,9999,1,0,NaN,NaN,8,0,9999
27090,26986141,Studio Suite,176952168,Aka,Manhattan,Financial District,40.70780,-74.00749,Entire home/apt,9999,1,0,NaN,NaN,8,0,9999
27091,26986636,Two Bedroom Suite,176952168,Aka,Manhattan,Financial District,40.70832,-74.00656,Entire home/apt,9999,1,1,2018-09-22,0.04,8,0,9999
27092,26986979,Two Bedroom Terrace Penthouse Suite,176952168,Aka,Manhattan,Financial District,40.70912,-74.00672,Entire home/apt,9999,1,0,NaN,NaN,8,0,9999
27093,26987123,Studio Premium Suite,176952168,Aka,Manhattan,Financial District,40.70821,-74.00682,Entire home/apt,9999,1,3,2020-03-15,0.40,8,0,9999
27976,28132020,King Suite at AKA Tribeca,212484716,AKA Tribeca,Manhattan,Midtown,40.75726,-73.96407,Private room,9999,1,0,NaN,NaN,7,0,9999
27977,28132057,Penthouse Suite at AKA Tribeca,212484716,AKA Tribeca,Manhattan,Midtown,40.75718,-73.96484,Private room,9999,1,0,NaN,NaN,7,0,9999
27978,28132121,Premier Suite at AKA Tribeca,212484716,AKA Tribeca,Manhattan,Midtown,40.75866,-73.96392,Private room,9999,1,0,NaN,NaN,7,0,9999
27979,28132224,Standard Double at AKA Tribeca,212484716,AKA Tribeca,Manhattan,Midtown,40.75714,-73.96570,Private room,9999,1,1,2018-10-07,0.04,7,0,9999
27980,28132251,Standard King at AKA Tribeca,212484716,AKA Tribeca,Manhattan,Midtown,40.75907,-73.96495,Private room,9999,1,0,NaN,NaN,7,0,9999
27981,28132293,Standard Queen at AKA Tribeca,212484716,AKA Tribeca,Manhattan,Midtown,40.75866,-73.96540,Private room,9999,1,0,NaN,NaN,7,0,9999
27982,28132314,Superior King,212484716,AKA Tribeca,Manhattan,Midtown,40.75907,-73.96498,Private room,9999,1,1,2018-09-30,0.04,7,0,9999
27989,28135545,Stanton Place,57205301,Desireé,Manhattan,Lower East Side,40.71915,-73.98660,Private room,7000,1,0,NaN,NaN,1,0,7000
30095,30416355,Manhattan Mega Mansion!!!!,162299538,Matthew,Manhattan,Hell's Kitchen,40.76480,-73.98899,Entire home/apt,7500,2,2,2019-10-28,0.20,1,90,7500
31004,31219800,~New jersey loft,172226912,Rom,Manhattan,Murray Hill,40.75020,-73.97905,Shared room,10000,40,11,2019-08-31,0.65,1,179,10000
31120,31340283,2br - The Heart of NYC: Manhattans Lower East ...,4382127,Matt,Manhattan,Lower East Side,40.71980,-73.98566,Entire home/apt,9999,30,0,NaN,NaN,1,365,9999
32303,33014307,Midtown/ Upper East Side Studio Apartment,248471931,Corey,Manhattan,Upper East Side,40.76206,-73.96042,Entire home/apt,9992,1,1,2019-04-06,0.06,1,0,9992
33064,33998396,3000 sq ft daylight photo studio,3750764,Kevin,Manhattan,Chelsea,40.75060,-74.00388,Entire home/apt,6800,1,0,NaN,NaN,4,364,6800
35158,36056808,Luxury TriBeCa Apartment at an amazing price,271248669,Jenny,Manhattan,Tribeca,40.71206,-74.00999,Entire home/apt,6500,180,0,NaN,NaN,1,365,6500
36031,37059577,"Celebrity building, panoramic/uninterrupted views",278736146,Jack,Manhattan,Hell's Kitchen,40.75822,-73.99564,Private room,10000,2,5,2020-01-02,0.39,4,365,10000
36866,37961305,24 under 1-roof in MANHATTAN LUXURY. Free Park,71276635,Joe,Manhattan,Washington Heights,40.83523,-73.94378,Entire home/apt,5070,1,0,NaN,NaN,5,365,5070
38075,39100961,"Chambers Hotel, Chambers Hotel Queen - ADA",220229838,Chamber Hotel,Manhattan,Midtown,40.76225,-73.97463,Private room,10000,1,0,NaN,NaN,11,0,10000
38738,39574087,"The Allen Hotel, Deluxe Penthouse King Suite",266741420,The Allen Hotel,Manhattan,Lower East Side,40.71894,-73.99178,Private room,10000,1,0,NaN,NaN,5,365,10000
43269,42740774,Room with STUNNING view in Times Square MANHAT...,278736146,Jack,Manhattan,Hell's Kitchen,40.75893,-73.99533,Private room,7000,1,0,NaN,NaN,4,365,7000
43935,43139232,DON'T LOOK DOWN!,278736146,Jack,Manhattan,Hell's Kitchen,40.76033,-73.99603,Private room,6666,1,0,NaN,NaN,4,365,6666
44475,43398117,A TRUE CORONABARGAIN!,278736146,Jack,Manhattan,Hell's Kitchen,40.76017,-73.99429,Private room,6666,1,0,NaN,NaN,4,365,6666

In [59]:
# 6. What % of the rooms are private, and what % of the rooms are shared.  
select_condition1 = df["room_type"] == "Private room"
select_condition2 = df["room_type"] == "Shared room"

print("% of "+str( (df["room_type"][select_condition1].value_counts() / len(df)) *100))
print("% of "+str( (df["room_type"][select_condition2].value_counts() / len(df)) *100))

% of Private room    45.444581
Name: room_type, dtype: float64
% of Shared room    2.121349
Name: room_type, dtype: float64

In [60]:
#Challenge
df[df["name"].str.contains("brownstone",na = False, case = False)]

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,adjusted_price
29,12940,Charming Brownstone 3 - Near PRATT,50148,Adreinne,Brooklyn,Bedford-Stuyvesant,40.68111,-73.95591,Entire home/apt,100,5,66,2020-03-02,0.51,1,19,100
32,13394,Fort Greene brownstone,52335,Alexander,Brooklyn,Fort Greene,40.69142,-73.97376,Private room,70,1,143,2020-03-19,1.11,1,170,70
34,13808,Blue Room for 2 in Brownstone for $1350 monthly,54275,JT And Tiziana,Brooklyn,Bedford-Stuyvesant,40.68064,-73.94039,Private room,81,2,141,2020-07-12,1.14,3,339,81
70,20717,Room in Brownstone B/Q feet away,78353,Guillaume,Brooklyn,Prospect Heights,40.67832,-73.97243,Private room,85,1,43,2020-03-17,0.52,3,312,85
92,27006,Comfortable UWS 2-BD Family-Friendly Brownstone,115560,Stacy,Manhattan,Upper West Side,40.77823,-73.97637,Entire home/apt,225,6,28,2019-07-12,0.25,1,337,225
125,38663,Luxury Brownstone in Boerum Hill,165789,Sarah,Brooklyn,Boerum Hill,40.68559,-73.98094,Entire home/apt,650,3,23,2018-12-31,0.23,1,365,650
146,45910,Beautiful Queens Brownstone! - 5BR,204539,Mark,Queens,Ridgewood,40.70382,-73.89797,Entire home/apt,339,4,13,2019-11-12,0.12,5,365,339
151,46911,Large Room in private Brownstone in Park Slope,210746,Kathleen R.,Brooklyn,Prospect Heights,40.67868,-73.97307,Private room,100,3,51,2019-06-24,0.42,3,229,100
171,55498,Modern comfort in art infused landmark Brownstone,262138,Tami,Brooklyn,Bedford-Stuyvesant,40.68290,-73.93549,Private room,79,14,42,2020-03-15,0.36,1,108,79
180,57874,The Brownstone-Luxury 1 Bd Apt/NYC,276291,Simon,Manhattan,Harlem,40.80931,-73.94343,Entire home/apt,157,3,258,2020-08-07,2.17,2,319,157
190,60193,The Cozy Brownstone in Harlem,289838,Zakiya,Manhattan,Harlem,40.80481,-73.94777,Private room,150,3,2,2011-08-29,0.02,1,365,150
203,62430,BROWNSTONE SUNDRENCHED BEAUTY,197755,Sheila,Brooklyn,Bushwick,40.68800,-73.91710,Entire home/apt,72,7,129,2020-02-07,1.97,1,0,72
304,100368,Greenwich Village Brownstone -- Huge Private Deck,526105,Scott,Manhattan,Chelsea,40.74056,-74.00143,Entire home/apt,299,31,32,2019-07-05,0.29,1,349,299
306,102995,UWS Brownstone Near Central Park,178043,Chas,Manhattan,Upper West Side,40.78558,-73.96960,Entire home/apt,212,21,45,2018-01-01,0.40,1,44,212
355,141335,Architect's Brownstone,687361,Orna,Brooklyn,Park Slope,40.67535,-73.97654,Entire home/apt,685,1,35,2018-01-13,0.35,1,365,685
377,152263,Cozy apartment in a brownstone,732535,William,Manhattan,Harlem,40.80497,-73.95016,Entire home/apt,300,2,229,2020-03-08,2.11,3,325,300
387,159749,Purple Room for 2/3 in brownstone $1450 per month,54275,JT And Tiziana,Brooklyn,Bedford-Stuyvesant,40.68048,-73.93938,Private room,87,2,76,2020-01-03,0.71,3,348,87
388,159815,Red Room for two in Brownstone for $1355/mo,54275,JT And Tiziana,Brooklyn,Bedford-Stuyvesant,40.68048,-73.93938,Private room,78,7,51,2020-03-01,0.47,3,322,78
398,165080,Amazing Brownstone in Best Brooklyn,618702,Smadar,Brooklyn,Carroll Gardens,40.68090,-73.99233,Entire home/apt,500,7,7,2018-08-29,0.06,1,0,500
437,189787,Spacious & Comfy BK Brownstone,915640,Sundiata,Brooklyn,Crown Heights,40.66788,-73.94813,Entire home/apt,108,4,103,2020-01-01,0.94,1,0,108
439,190968,Lovely Brooklyn Brownstone 1BR!,922922,Karen,Brooklyn,Prospect Heights,40.67946,-73.96501,Entire home/apt,215,3,37,2019-12-28,0.34,1,177,215
463,205485,Ideal Brooklyn Brownstone Apartment,1010242,Zora & Chris,Brooklyn,Bedford-Stuyvesant,40.68186,-73.94113,Entire home/apt,145,3,135,2020-01-03,1.24,1,227,145
467,206473,FURNISHED BROWNSTONE DUPLEX in PARK SLOPE,888420,Ted,Brooklyn,Park Slope,40.67127,-73.97985,Entire home/apt,175,90,7,2014-05-27,0.09,1,57,175
505,228925,Beautiful Brownstone,1194377,Marceline,Brooklyn,Bedford-Stuyvesant,40.67964,-73.93946,Entire home/apt,100,30,10,2019-06-26,0.48,1,363,100
544,245574,Brooklyn Brownstone apartment,1288460,Al-,Brooklyn,Bedford-Stuyvesant,40.68890,-73.95383,Entire home/apt,80,2,185,2020-05-24,1.72,1,311,80
548,248717,Brownstone comfort + beautiful yard,1269526,Amy,Brooklyn,Park Slope,40.67360,-73.98113,Private room,65,1,14,2020-03-08,0.13,2,364,65
657,276317,"The Carlton, Brooklyn brownstone Duplex w/ garden",130901,Chauncey,Brooklyn,Prospect Heights,40.67847,-73.97038,Entire home/apt,550,3,105,2020-03-15,1.00,1,365,550
683,286838,Private Room in Brownstone,1492339,Karin,Manhattan,Harlem,40.80748,-73.95589,Private room,75,2,101,2015-10-31,0.96,1,0,75
686,287421,"Cozy, Clean Cobble Hill Brownstone",1495141,Keow,Brooklyn,Cobble Hill,40.68538,-74.00056,Entire home/apt,140,3,103,2017-08-01,0.99,1,228,140
774,342995,Unique private room and bathroom in Brownstone,1740216,Laura,Manhattan,Harlem,40.81169,-73.94355,Private room,90,2,88,2019-11-30,0.87,2,179,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43783,43071163,Beautiful 1br in UWS brownstone on Central Park,4335378,Madeleine,Manhattan,Upper West Side,40.78692,-73.96869,Entire home/apt,87,6,1,2020-05-13,0.32,1,0,87
43843,43103808,Beautiful Brownstone Apt.,79720116,Cheri,Manhattan,Harlem,40.80727,-73.95054,Entire home/apt,90,30,0,NaN,NaN,1,365,90
43848,43105265,Sun Drenched Duplex in Bed Stuy Brownstone,2065732,Nicole,Brooklyn,Bedford-Stuyvesant,40.68531,-73.94517,Entire home/apt,155,3,0,NaN,NaN,1,88,155
44009,43170693,Brownstone Living with amazing Views!,254420231,Efron,Brooklyn,Bedford-Stuyvesant,40.69039,-73.94224,Entire home/apt,171,1,8,2020-07-25,2.82,1,227,171
44109,43220447,Brooklyn's Best- Sunny & Spacious Brownstone Apt,238380801,Brooklyn,Brooklyn,Fort Greene,40.68801,-73.97699,Entire home/apt,124,3,1,2020-07-31,1.00,1,338,124
44243,43299277,Airy Brooklyn Brownstone - 20% off monthly stays,10782510,Calen,Brooklyn,Clinton Hill,40.68726,-73.96286,Entire home/apt,150,1,1,2020-06-24,0.56,1,8,150
44400,43367498,Huge light-filled historic brownstone,43232214,Nicholas,Brooklyn,Bedford-Stuyvesant,40.68067,-73.93423,Entire home/apt,200,14,0,NaN,NaN,1,103,200
44591,43457355,"Monthly Stay: Large brownstone 1bed, summer he...",4401257,Elizabeth,Brooklyn,Boerum Hill,40.68690,-73.98666,Entire home/apt,75,30,1,2020-08-04,1.00,1,70,75
44612,43466988,Modern brownstone apartment with garden,9407935,Benjamin,Brooklyn,Carroll Gardens,40.68046,-73.99905,Entire home/apt,250,29,0,NaN,NaN,1,108,250
44667,43498999,Gorgeous Bohemian Duplex in Historic Brownstone,66286,Liat,Brooklyn,Bedford-Stuyvesant,40.68487,-73.94075,Entire home/apt,150,1,0,NaN,NaN,3,0,150
44735,43546378,Cozy zen sanctuary w/ garden I Brooklyn browns...,18895623,Nick & Eunice,Brooklyn,Bedford-Stuyvesant,40.68340,-73.92770,Entire home/apt,100,30,1,2020-07-11,0.81,1,71,100
45079,43766271,Hip and Historic Harlem Brownstone Apt.,60063052,Lori,Manhattan,Harlem,40.82702,-73.94235,Entire home/apt,149,31,0,NaN,NaN,1,365,149
45100,43778233,Park Slope 2 BD Brownstone Apt with Private Ga...,1826093,Jack,Brooklyn,Park Slope,40.67144,-73.97444,Entire home/apt,275,4,0,NaN,NaN,1,250,275
45149,43813411,"Luxury apt in a Brownstone in Sobro, The Bronx",74024064,Michael,Bronx,Hunts Point,40.81550,-73.88694,Entire home/apt,98,1,19,2020-08-12,9.66,1,164,98
45176,43824388,Beautiful Brownstone apartment in Park Slope,350484704,Marie,Brooklyn,Park Slope,40.67610,-73.97388,Entire home/apt,160,5,0,NaN,NaN,1,112,160
45184,43831018,Park Slope Brownstone - entire floor,7478124,Igor,Brooklyn,Park Slope,40.67547,-73.97667,Entire home/apt,165,3,2,2020-07-12,1.30,1,20,165
45227,43862926,Sunny 2BR in Historic Bed-Stuy Brownstone,5684621,Maggie,Brooklyn,Bedford-Stuyvesant,40.68945,-73.95428,Entire home/apt,95,7,2,2020-07-24,1.50,1,227,95
45294,43906386,"Brooklyn brownstone on quiet, tree-lined block.",9742120,Jeffrey,Brooklyn,Sunset Park,40.64669,-74.00790,Entire home/apt,110,7,0,NaN,NaN,1,0,110
45335,43928399,One Bedroom Brownstone Beauty,9717514,Jacqueline,Brooklyn,Sunset Park,40.65360,-74.00493,Entire home/apt,150,3,0,NaN,NaN,1,336,150
45571,44073380,Brownstone Studio w/Loft Bedroom by Ft Greene ...,322423295,Michele,Brooklyn,Fort Greene,40.69104,-73.96955,Entire home/apt,75,28,0,NaN,NaN,1,6,75
45656,44154139,Modern Equipped Studio in Bed Stuy Brownstone,49293531,Aliza,Brooklyn,Bedford-Stuyvesant,40.68416,-73.92762,Entire home/apt,90,14,1,2020-08-08,1.00,4,261,90
45743,44210249,Brooklyn brownstone with outdoor space,13098239,Blair,Brooklyn,Clinton Hill,40.68451,-73.96213,Entire home/apt,144,14,0,NaN,NaN,1,30,144
45866,44304516,Central Park Brownstone studio & Private terrace,2644100,Jojo,Manhattan,Upper West Side,40.77929,-73.98380,Entire home/apt,110,10,0,NaN,NaN,1,173,110
45988,44363142,"Beautiful, serene brownstone with outdoor space",16256520,Rochelle,Brooklyn,Bedford-Stuyvesant,40.68302,-73.95782,Entire home/apt,500,4,0,NaN,NaN,1,26,500
46191,44503706,Huge 1 Bed in a Private Historic Brownstone,209279462,Rodrigo,Manhattan,East Harlem,40.79949,-73.93550,Entire home/apt,88,3,0,NaN,NaN,3,358,88
46220,44531911,Private 2 Bed in Historic Brownstone,209279462,Rodrigo,Manhattan,East Harlem,40.79928,-73.93514,Entire home/apt,144,3,0,NaN,NaN,3,355,144
46337,44625524,Renovated Brownstone w/ Yard Near Prospect Park,2771914,Ian,Brooklyn,Windsor Terrace,40.65772,-73.97696,Entire home/apt,995,5,0,NaN,NaN,1,23,995
46349,44631837,Unique and Stylish Park Slope Brownstone triplex,40231738,Thatcher,Brooklyn,Park Slope,40.67032,-73.98052,Entire home/apt,400,30,0,NaN,NaN,2,265,400
46390,44658559,Clean Room w/ Outdoor Deck in Brooklyn Brownstone,4393745,Nelson,Brooklyn,Bedford-Stuyvesant,40.68289,-73.95348,Private room,40,4,0,NaN,NaN,1,74,40
46401,44661851,Luxury Nest in the Sky in a Brownstone,100671934,Fannie,Manhattan,Greenwich Village,40.73145,-73.99466,Entire home/apt,532,29,0,NaN,NaN,2,178,532

# Exercise 3 - Grouping

1. Using `groupby`, count how many listings are in each neighbourhood_group.


2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 


3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 


4. Using `groupby`, find the median price for each room type in each neighbourhood_group.


5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices for each room type in each neighbourhood_group.

In [61]:
# 1. Using `groupby`, count how many listings are in each neighbourhood_group.
df.groupby('neighbourhood_group')["id"].count()

neighbourhood_group
Bronx             1183
Brooklyn         18632
Manhattan        20580
Queens            5791
Staten Island      341
Name: id, dtype: int64

In [62]:
# 2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 
df.groupby('neighbourhood_group')["price"].mean()

neighbourhood_group
Bronx             92.751479
Brooklyn         120.225258
Manhattan        191.880466
Queens            99.754965
Staten Island    110.947214
Name: price, dtype: float64

In [63]:
# 3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 
df.groupby('neighbourhood_group')['price'].agg(['min', 'max'])

                     min    max
neighbourhood_group
Bronx                 16   1404
Brooklyn               0  10000
Manhattan              0  10000
Queens                 0  10000
Staten Island         19   1200

In [64]:
# 4. Using `groupby`, find the mean price for each room type in each neighbourhood_group.
df.groupby(['neighbourhood_group','room_type'])["price"].mean()

neighbourhood_group  room_type
Bronx                Entire home/apt    138.004819
                     Private room        68.419668
                     Shared room         66.391304
Brooklyn             Entire home/apt    171.587687
                     Hotel room         147.300000
                     Private room        71.291189
                     Shared room         57.870091
Manhattan            Entire home/apt    231.335572
                     Hotel room         292.515670
                     Private room       128.277069
                     Shared room        111.735084
Queens               Entire home/apt    150.168900
                     Hotel room         139.058824
                     Private room        69.972564
                     Shared room         89.891892
Staten Island        Entire home/apt    151.720930
                     Private room        70.312883
                     Shared room         46.000000
Name: price, dtype: float64

In [65]:
# 5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices 
# for each room type in each neighbourhood_group.
gbList = ['neighbourhood_group','room_type']
df.groupby(gbList)["price"].agg( ["count","min","max","mean","median","std"] )

                                     count  min    max        mean  median  \
neighbourhood_group room_type
Bronx               Entire home/apt    415   25   1404  138.004819     103
                    Private room       722   16    700   68.419668      55
                    Shared room         46   20    800   66.391304      44
Brooklyn            Entire home/apt   9112   20  10000  171.587687     135
                    Hotel room          30    0    399  147.300000     129
                    Private room      9159   10   2500   71.291189      60
                    Shared room        331   15   1500   57.870091      36
Manhattan           Entire home/apt  12209    0  10000  231.335572     165
                    Hotel room         351    0   2211  292.515670     210
                    Private room      7601   10  10000  128.277069      80
                    Shared room        419   10  10000  111.735084      60
Queens              Entire home/apt   2090   10  10000  150.168900     115
                    Hotel room          17    0    249  139.058824     149
                    Private room      3499   18   9000   69.972564      55
                    Shared room        185   14   3000   89.891892      40
Staten Island       Entire home/apt    172   39   1200  151.720930     111
                    Private room       163   20    800   70.312883      55
                    Shared room          6   19     82   46.000000      38

                                            std
neighbourhood_group room_type
Bronx               Entire home/apt  126.032106
                    Private room      57.337866
                    Shared room      114.442703
Brooklyn            Entire home/apt  236.732843
                    Hotel room        91.153206
                    Private room      69.023165
                    Shared room       92.217618
Manhattan           Entire home/apt  410.306439
                    Hotel room       315.924085
                    Private room     448.677306
                    Shared room      502.728868
Queens              Entire home/apt  252.606739
                    Hotel room        50.743806
                    Private room     163.814468
                    Shared room      275.675158
Staten Island       Entire home/apt  147.518392
                    Private room      70.759593
                    Shared room       28.446441

# Join and file saving.
1. Load the `prices.csv` and the `n_listings.csv`


2. Do join that keeps all the records for each table.
    * Neighbourhood groups should include ['Bronx', 'Brooklyn', 'Manhattan', 'Queens', 'Staten Island',
       'LongIsland']
       
       
3. Save your joined csv as `joined.csv`


4. Load your saved table and see if it looks the same or different that the DataFrame you used to create it.

In [66]:
# 1. Load the `prices.csv` and the `n_listings.csv`
pricesDF = pd.read_csv('data/prices.csv', sep=',')
nlistingsDF = pd.read_csv('data/n_listings.csv', sep=';')

In [67]:
# 2. Do join that keeps all the records for each table.
mergeDF = pd.merge(pricesDF, nlistingsDF, on='neighbourhood_group', how='outer')

save_as = 'joined.csv'

mergeDF.to_csv(save_as, index=False)

# Use the grammys.csv data for the next section of questions.

1. Who was won Album of the Year in 2016?


2. Who won Best Rap Album in 2009?


3. How many awards was Kendrick Lamar nomiated for, and how many did he win...?

In [68]:
#  1. Who was won Album of the Year in 2016?
grammyDF = pd.read_csv('data/grammys.csv',sep=",")
select = grammyDF["category"] == "Album of the Year"
select2 = grammyDF["year"] == 2016
select3 = grammyDF["winner"] == True

print(grammyDF[select & select2 & select3]["workers"].to_string())

5505    Taylor Swift (artist/producer), Jack Antonoff ...

In [69]:
# 2. Who won Best Rap Album in 2009?
select = grammyDF["category"] == "Best Rap Album"
select2 = grammyDF["year"] == 2009
select3 = grammyDF["winner"] == True

print(grammyDF[select & select2 & select3]["workers"].to_string())

4396    Lil' Wayne

In [70]:
# 3. How many awards was Kendrick Lamar nomiated for, and how many did he win...?
select1 = grammyDF["workers"].isin( ["Kendrick Lamar"] )
select2 = grammyDF["winner"] == True
print("Nomination: "+str(grammyDF[select1]["winner"].count()))
grammyDF[select1]

Nomination: 6

,year,category,nominee,workers,winner
5269,2014,Best Rap Album,"Good Kid, M.A.A.D City.",Kendrick Lamar,False
5272,2014,Best Rap Performance,Swimming Pools (Drank).,Kendrick Lamar,False
5448,2015,Best Rap Performance,i.,Kendrick Lamar,True
5596,2016,Best Rap Album,To Pimp a Butterfly.,Kendrick Lamar,True
5599,2016,Best Rap Performance,Alright.,Kendrick Lamar,True
6003,2018,Best Rap Performance,HUMBLE.,Kendrick Lamar,True

In [71]:
print("Winner: "+str(grammyDF[select1 & select2]["winner"].count()))
grammyDF[select1 & select2]

Winner: 4

      year              category               nominee         workers  winner
5448  2015  Best Rap Performance                    i.  Kendrick Lamar    True
5596  2016        Best Rap Album  To Pimp a Butterfly.  Kendrick Lamar    True
5599  2016  Best Rap Performance              Alright.  Kendrick Lamar    True
6003  2018  Best Rap Performance               HUMBLE.  Kendrick Lamar    True